[workspace]
exclude = ["vdso-gen"]

[package]
name = "linux-raw-vdso"
version = "0.0.1"
edition = "2018"

# [dev-dependencies]
# linux-auxv = { git = "https://www.github.com/shurizzle/linux-auxv" }

[dependencies]
