[package]
name = "vdso-gen"
version = "0.0.1"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
proc-macro2 = "1.0.58"
quote = "1.0.27"
syn = { version = "2.0.16", features = ["full"] }
which = "4.4.0"
